### ISSUE TITLE
Incomplete data

### ISSUE THREAD

**Issue by lywinaaa** [justsmart/RecFormer#1]
How the “percentDel_0.5.mat” is obtained

**Comment by justsmart** [comment]
All you need to do is generate a matrix of shape n*m with all elements 1 (n for the number of samples, m for the number of views), and follow the rule to set 50% of the 1 to 0. The specific rule is: set the random half of the elements in each column of the matrix to 0, and then check if at least one view is available for each sample, if not, you need to fine-tune the position of the 0 and 1 elements in the matrix until the requirement is met.

**Comment by justsmart** [comment]
And this generation process requires you to implement using the Matlab or python

**Comment by lywinaaa** [comment]
> 而这个生成过程需要你使用Matlab或python来实现

Hello, first of all, thank you very much for your reply, because I am new to this field, so I may not understand what you said, if possible, can you provide your code for constructing incomplete data? Or existing incomplete datasets from your thesis experiments. Finally, I wish you smooth work and good health!

**Comment by lywinaaa** [comment]
> 而这个生成过程需要你使用Matlab或python来实现

您好，还有个问题就是您为了减少实验随机性，一般都是执行几次试验

**Comment by justsmart** [comment]
> > 而这个生成过程需要你使用Matlab或python来实现
> 
> 您好，还有个问题就是您为了减少实验随机性，一般都是执行几次试验

一般5-10次重复实验

**Comment by d6h2p** [comment]
Can you provide the code to construct an incomplete dataset

**Comment by G-Morgen** [comment]
> Can you provide the code to construct an incomplete dataset

import numpy as np
import random

def splitDigitData(N, V, inCP, seed=1):
    """
    Function to split digit data based on specified criteria.

    Parameters:
        N (int): The total number of items.
        V (int): The number of views. 
        inCP (float): The fraction of items to be excluded initially. such as 0.5
        seed (int): The random seed for reproducibility.

    Returns:
        splitInd (numpy.ndarray): An array indicating the split of data.
    """
    # Initialize the split index matrix
    splitInd = np.ones((N, V), dtype=int)
    
    # Create a list for random permutations of indices
    indCell = [None] * V
    
    # Calculate the number of elements to delete
    delNum = int(np.floor(N * inCP))
    
    # Set the random seed
    random.seed(seed)
    np.random.seed(seed)
    
    # Generate random permutations and initialize the splitInd matrix
    for i in range(V):
        indCell[i] = np.random.permutation(N)
        splitInd[indCell[i][:delNum], i] = 0
    
    # Counter to track the next index to switch to 0 in each group
    counter = np.array([delNum + 1] * V)
    
    # Resolve cases where a row in splitInd is all zeros
    while True:
        zerosInd = np.where(np.sum(splitInd, axis=1) == 0)[0]
        if zerosInd.size == 0:
            break
        else:
            i = random.randint(0, V - 1)
            splitInd[zerosInd[0], i] = 1
            if counter[i] < N:  # Check to avoid index error
                splitInd[indCell[i][counter[i]], i] = 0
                counter[i] += 1
    
    return splitInd

**Comment by justsmart** [comment]
> Can you provide the code to construct an incomplete dataset

import numpy as np
import random

def splitDigitData(N, V, inCP, seed=1):
    """
    Function to split digit data based on specified criteria.

    Parameters:
        N (int): The total number of items.
        V (int): The number of views. 
        inCP (float): The fraction of items to be excluded initially. such as 0.5
        seed (int): The random seed for reproducibility.

    Returns:
        splitInd (numpy.ndarray): An array indicating the split of data.
    """
    # Initialize the split index matrix
    splitInd = np.ones((N, V), dtype=int)
    
    # Create a list for random permutations of indices
    indCell = [None] * V
    
    # Calculate the number of elements to delete
    delNum = int(np.floor(N * inCP))
    
    # Set the random seed
    random.seed(seed)
    np.random.seed(seed)
    
    # Generate random permutations and initialize the splitInd matrix
    for i in range(V):
        indCell[i] = np.random.permutation(N)
        splitInd[indCell[i][:delNum], i] = 0
    
    # Counter to track the next index to switch to 0 in each group
    counter = np.array([delNum + 1] * V)
    
    # Resolve cases where a row in splitInd is all zeros
    while True:
        zerosInd = np.where(np.sum(splitInd, axis=1) == 0)[0]
        if zerosInd.size == 0:
            break
        else:
            i = random.randint(0, V - 1)
            splitInd[zerosInd[0], i] = 1
            if counter[i] < N:  # Check to avoid index error
                splitInd[indCell[i][counter[i]], i] = 0
                counter[i] += 1
    
    return splitInd

**Comment by d6h2p** [comment]
Do I need to use this code in train.py to process the dataset

**Comment by justsmart** [comment]
> Do I need to use this code in train.py to process the dataset

I suggest that you could use the function to construct the incomplete index matrix before running train.py.
In fact, our incomplete data index matrix is constructed by MATLAB code and stored in .mat file like "handwritten-5view_percentDel_0.5.mat" in the data folder. But now, you can also construct the index matrix by modifying the "mydataset.py" via the python code I just provided to you.

**Comment by d6h2p** [comment]
> > 是否需要在 train.py 中使用此代码来处理数据集
> 
> 我建议您在运行 train.py 之前使用该函数构造不完整的索引矩阵。事实上，我们的不完整数据索引矩阵是由 MATLAB 代码构建的，并存储在 data 文件夹中的 .mat 文件中，如 “handwritten-5view_percentDel_0.5.mat”。但是现在，你也可以通过我刚刚提供给你的 python 代码修改 “mydataset.py” 来构造索引矩阵。

Is fold_mat_path in mydataset.py a generated missing rate dataset? Do we need the code provided above to construct other missing rate datasets？

**Comment by justsmart** [comment]
Yes, you should construct two datasets, the one is the raw complete data, and the other one is the missing index matrix that is stored in “fold_mat_path”

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/10/2024 20:02 |
| To | justsmart/RecFormer ***@***.***> |
| Cc | Liu ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [justsmart/RecFormer] Incomplete data (Issue #1) |

是否需要在 train.py 中使用此代码来处理数据集

我建议您在运行 train.py 之前使用该函数构造不完整的索引矩阵。事实上，我们的不完整数据索引矩阵是由 MATLAB 代码构建的，并存储在 data 文件夹中的 .mat 文件中，如 “handwritten-5view_percentDel_0.5.mat”。但是现在，你也可以通过我刚刚提供给你的 python 代码修改 “mydataset.py” 来构造索引矩阵。

Is fold_mat_path in mydataset.py a generated missing rate dataset? Do we need the code provided above to construct other missing rate datasets？

**Comment by d6h2p** [comment]
Do train1 and train2 in train.py correspond to stage1 and stage2 in the model diagram respectively？

**Comment by justsmart** [comment]
> Do train1 and train2 in train.py correspond to stage1 and stage2 in the model diagram respectively？

Yes!

**Comment by d6h2p** [comment]
Is trg loaded from the dataset？

**Comment by d6h2p** [comment]
Is the trg in model. py loaded from the dataset？

**Comment by d6h2p** [comment]
Should the trg in model. py be None？

**Comment by justsmart** [comment]
> Should the trg in model. py be None？

Yes, we do not use the TransformerWoDecoder, trg_mask is ignorable.

**Comment by d6h2p** [comment]
Is not using TransformerWoDecoder for further processing of cross view features

**Comment by justsmart** [comment]
> Is not using TransformerWoDecoder for further processing of cross view features

Yes, I will delete that module in model.py.

**Comment by d6h2p** [comment]
Doesn't the decoder function need to be implemented in the Model class？

**Comment by justsmart** [comment]
> Doesn't the decoder function need to be implemented in the Model class？

The encoder and decoder are implemented by the same module named "Transformer"

**Comment by d6h2p** [comment]
Can you provide the Animals dataset and NH_FACE dataset?
| |
LWJ
|
|
***@***.***
|
---- Replied Message ----
| From | Liu ***@***.***> |
| Date | 12/3/2024 20:16 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [justsmart/RecFormer] Incomplete data (Issue #1) |

Closed #1 as completed.

**Comment by justsmart** [comment]
> Can you provide the Animals dataset and NH_FACE dataset?
> | |
> LWJ
> |
> |
> ***@***.***
> |
> ---- Replied Message ----
> | From | Liu ***@***.***> |
> | Date | 12/3/2024 20:16 |
> | To | ***@***.***> |
> | Cc | ***@***.***> ,
> ***@***.***> |
> | Subject | Re: [justsmart/RecFormer] Incomplete data (Issue [#1](https://github.com/justsmart/RecFormer/issues/1)) |
> 
> Closed [#1](https://github.com/justsmart/RecFormer/issues/1) as completed.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

NH_face: https://drive.google.com/file/d/1SyO15SN9HmBHROxKu9KaKxEaGFnQg_VT/view?usp=sharing
Animal: https://drive.google.com/file/d/1F5nvMXr97_isln6-XVDcwNqMpegw7sQi/view?usp=sharing
